"""fix property coordinates precision

Revision ID: 9f5d648d5714
Revises: f2a89a65492f
Create Date: 2026-08-26 13:59:02.299772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5d648d5714'
down_revision: Union[str, Sequence[str], None] = 'f2a89a65492f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'latitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=11, scale=8),
               existing_nullable=True)
    op.alter_column('properties', 'longitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=11, scale=8),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'longitude',
               existing_type=sa.Numeric(precision=11, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('properties', 'latitude',
               existing_type=sa.Numeric(precision=11, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    # ### end Alembic commands ###
